branch-defaults:
  master:
    environment: pintrestclone2-env
environment-defaults:
  pintrestclone-env:
    branch: null
    repository: null
  pintrestclone2-env:
    branch: null
    repository: null
global:
  application_name: PintrestClone
  default_ec2_keyname: keyForPintrest
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Puma with Ruby 2.4
    running on 64bit Amazon Linux/2.6.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
